name: Auto Commit

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every 1 minutes

jobs:
  commit:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Modify file
        run: echo "$(date)" >> dummy.txt

      - name: Commit changes
        run: |
          git config --global user.name "FotomCTO"
          git config --global user.email "fang79216@gmail.com"
          git add dummy.txt
          git commit -m "Auto commit - $(date)" || echo "No changes to commit"
          git push